fix: handle invalid json / string body
smartcar/java-sdk pull request #86
Opened 2020-10-22 22:32 UTC by s-ashwinkumar

Asana: https://app.asana.com/0/1198085188814749/1197421727948877

2020-10-22 23:10 UTC, s-ashwinkumar commented on src/main/java/com/smartcar/sdk/SmartcarException.java
> +    JsonObject body;
Adding comment so this pops up on PR main page.

2020-10-23 17:46 UTC, sankethkatta requested changes
This solves the issue at hand.

2020-10-23 17:46 UTC, sankethkatta commented on src/main/java/com/smartcar/sdk/SmartcarException.java
> +    }catch (com.google.gson.JsonParseException exception) {
nit: spacing
```suggestion
    } catch (com.google.gson.JsonParseException exception) {
```

2020-10-23 17:46 UTC, sankethkatta commented on src/main/java/com/smartcar/sdk/SmartcarException.java
> +    }
add another generic `catch` for any other error that could be thrown and raise it as a `SmartcarException`

2020-10-23 19:45 UTC, sankethkatta approved these changes

2020-10-27 23:31 UTC, merged